### PR TITLE
Add links to solution pages

### PR DESCRIPTION
**Pull request by karenzone**
## Release notes
[rn:skip]

## What does this PR do?
Adds links to Elastic Enterprise Search solutions pages

### CODE REVIEW

**Comment by karenzone** [comment]
@andsel I approved and merged #9 as we discussed. Please review and let me know if I'm clear to merge and publish pending your approval.

**Comment by karenzone** [comment]
@karenzone Note to self: Make sure that the published date/version is working correctly for app_search. If not, figure out what's wrong.

**Review by andsel — APPROVED** [review]
LGTM

**Comment by karenzone** [comment]
Published at v2.1.2: https://rubygems.org/gems/logstash-integration-elastic_enterprise_search/versions/2.1.2

**Pull request merged**
